Installing required packages and imported 

In [9]:
import numpy as np
import dual_quaternions as DQ
import scipy as sp

D-H Parameters of UR5, 6-revolute(6R), Reach:~850mm, Payload: 5Kg, All measurements in Metric (M/mm).

ai-1 alpi-1 di thetai
1 0 0 127.3
2 0 -pi/2 0
3 -425.0 0 0
4 -392.25 0 109.15
5 0 pi/2 94.65
6 0 -pi/2 82.3

In [10]:
a = np.array([0.0,0.0,-0.42500,-0.39225,0.0,0.0])
alpha = np.array([0.0,-(np.pi/2),0.0,0.0,(np.pi/2),-(np.pi/2)])
d = np.array([0.1273,0.0,0.0,0.10915,0.09465,0.0823])
theta = np.array([0.0,0.0,0.0,0.0,0.0,0.0])
dh = np.array([a,
               alpha,
               d,
               theta])
print(dh)

[[ 0.          0.         -0.425      -0.39225     0.          0.        ]
 [ 0.         -1.57079633  0.          0.          1.57079633 -1.57079633]
 [ 0.1273      0.          0.          0.10915     0.09465     0.0823    ]
 [ 0.          0.          0.          0.          0.          0.        ]]


Building Joint axis in world/Space frame/Screw axis

Joint axis direction at zero config:

Joint 1: rotates about Z-axis of base
w1 = [0,0,1]
Joint 2: rotates about Y-axis (after alpha1 = -pi/2 rotation about X)
w2 = [0,1,0]
Joint 3: rotates about Y-axis (same as joint 2 in zero config)
w3 = [0,1,0]
Joint 4: rotates about Y-axis
w4 = [0,1,0]
Joint 5: rotates about Z-axis (after alpha 4 = pi/2)
w5 = [0,0,-1]
Joint 6: rotates about Y-axis (after alpha 5 = -pi/2)
w6 = [0,1,0]

In [12]:
w1 = np.array([0.,0.,1.])
w2 = np.array([0.,1.,0.])
w3 = np.array([0.,1.,0.])
w4 = np.array([0.,1.,0.])
w5 = np.array([0.,0.,-1.])
w6 = np.array([0.,1.,0.])
wn = np.array([w1,
               w2,
               w3,
               w4,
               w5,
               w6])
print(wn)

[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


Point on each joint axis at Zero Config (origin of each joint):

joint 1 at base origin
q1 = [0,0,0]
Joint 2 lifted by d1
q2 = [0,0,0.1273]
Joint 3 (a2 = d along world x at zero config)
q3 = [-0.425,0,0.1273]
Joint 4 (d4 is along the Z-axis of frame 3, which at zero point in world Z
q4 = [-0.425 + (-0.39225),0,0.1273+d4.(0)]
   =[-0.81725,0,0.22195]
Joint 5 ( q4 + d5 along frame-4 Z-axis frame 4 Z-axis at zero = world Z
q5 = [-0.81725,0,0.1273+0.09465]
   = [-0.81725,0,0.22195]
joint 6 (q5 + 0 displacment, d6 along frame-5 Z)
frame 5 Z = world Y ( because alph 4 = pi/2 flipped Z into Y)
= [ -0.81725, d6, 0.22195]
q6 = [-0.81725,0.19145,0.00550]
same as end effector at zero

In [13]:
q1 = np.array([0.,0.,0.])
q2 = np.array([0.,0.,0.1273])
q3 = np.array([-0.425,0.,0.1273])
q4 = np.array([-0.81725,0.,0.1273])
q5 = np.array([-0.81725,0.,0.22195])
q6 = np.array([-0.81725,0.19145,0.00550])
qn = np.array([q1,
               q2,
               q3,
               q4,
               q5,
               q6])
print(qn)

[[ 0.       0.       0.     ]
 [ 0.       0.       0.1273 ]
 [-0.425    0.       0.1273 ]
 [-0.81725  0.       0.1273 ]
 [-0.81725  0.       0.22195]
 [-0.81725  0.19145  0.0055 ]]
